import { Medication } from '../../types/formulary';

export interface ScreenshotItem {
  id: string;
  title: string;
  description: string;
  src: string;
}

export const INTRO_SCREENSHOTS: ScreenshotItem[] = [
  {
    id: 'dark-mode',
    title: 'Dark Mode Dashboard',
    description: 'High-contrast dark mode surface designed for nocturnal clinical shifts.',
    src: `${import.meta.env.BASE_URL}intro-assets/main-screen-dark-mode.png`,
  },
  {
    id: 'light-mode',
    title: 'Light Mode Dashboard',
    description: 'Clean, accessible light theme with brand teal accents for daylight consultation.',
    src: `${import.meta.env.BASE_URL}intro-assets/main-screen-light-mode.png`,
  },
  {
    id: 'quick-search',
    title: 'Multi-Field Instant Search',
    description: 'Fuzzy search by brand name, generic name, MDC code, or clinical indication.',
    src: `${import.meta.env.BASE_URL}intro-assets/quick-search-on-medication.png`,
  },
  {
    id: 'recent-searches',
    title: 'Recent Lookup History',
    description: 'Quick-access ribbon storing recent formulation lookups for single-tap replay.',
    src: `${import.meta.env.BASE_URL}intro-assets/recent-searches-ribbon.png`,
  },
  {
    id: 'quota-filter',
    title: 'Quota Control Filter',
    description: 'One-tap toggle isolating the 16 high-risk quota-controlled formulations.',
    src: `${import.meta.env.BASE_URL}intro-assets/List-quota-drugs-button.png`,
  },
  {
    id: 'neon-quota-alert',
    title: 'Neon Quota Visual Alerts',
    description: 'High-visibility neon amber glowing borders and warning badges for quota items.',
    src: `${import.meta.env.BASE_URL}intro-assets/neon-yellow-alert-on-quota-drugs.png`,
  },
  {
    id: 'med-detail',
    title: 'Clinical Guideline Card',
    description: 'Full prescribing restrictions, MAL registration links, dosage, and adverse reactions.',
    src: `${import.meta.env.BASE_URL}intro-assets/medication-detail-card.png`,
  },
  {
    id: 'settings',
    title: 'App Configuration & Sync',
    description: 'Check Google Sheets dataset updates, toggle orientation lock, and replay interactive tour.',
    src: `${import.meta.env.BASE_URL}intro-assets/setting-page.png`,
  },
];

export const INTRO_SAMPLE_MEDICATIONS: Medication[] = [
  {
    id: 'intro-med-1',
    name: 'Amlodipine Besilate 5mg Tablet',
    malBrands: 'MAL19984123A (Norvasc, Amlong)',
    fukkmSystemGroup: 'Cardiovascular System',
    mdc: 'C08CA01000T1001XX',
    neml: 'Yes',
    methodOfPurchase: 'APPL',
    prescriberCategory: 'B',
    indications: 'Essential hypertension, chronic stable angina pectoris.',
    prescribingRestrictions: 'None',
    dosage: 'Initial 5mg once daily; may increase to maximum 10mg once daily.',
    adverseReaction: 'Peripheral edema, dizziness, flushing, palpitations, fatigue.',
    contraindications: 'Severe hypotension, hypersensitivity to dihydropyridines.',
    interactions: 'Simvastatin (limit to 20mg daily), CYP3A4 inhibitors (ketoconazole).',
    precautions: 'Severe aortic stenosis, severe hepatic impairment, pregnancy.',
    isQuota: false,
  },
  {
    id: 'intro-med-2',
    name: 'Metformin HCl 500mg Tablet',
    malBrands: 'MAL19910456A (Glucophage, Diaformin)',
    fukkmSystemGroup: 'Alimentary Tract and Metabolism',
    mdc: 'A10BA02000T1001XX',
    neml: 'Yes',
    methodOfPurchase: 'APPL',
    prescriberCategory: 'B',
    indications: 'Type 2 diabetes mellitus, especially in overweight patients.',
    prescribingRestrictions: 'None',
    dosage: '500mg BD with or after meals; titrate up to 1000mg BD or 850mg TDS.',
    adverseReaction: 'Gastrointestinal upset, diarrhea, nausea, metallic taste.',
    contraindications: 'eGFR < 30 mL/min/1.73m², acute metabolic acidosis, severe hypoxia.',
    interactions: 'Iodinated contrast media (withhold 48h before/after), alcohol.',
    precautions: 'Monitor renal function annually; monitor Vitamin B12 levels periodically.',
    isQuota: false,
  },
  {
    id: 'intro-med-3',
    name: 'Insulin Aspart 100 IU/ml Solution for Injection (FlexPen)',
    malBrands: 'MAL20013456A (NovoRapid)',
    fukkmSystemGroup: 'Alimentary Tract and Metabolism',
    mdc: 'A10AB05000P3001XX',
    neml: 'Yes',
    methodOfPurchase: 'Contract',
    prescriberCategory: 'A/KK',
    indications: 'Treatment of diabetes mellitus requiring rapid-acting prandial insulin.',
    prescribingRestrictions: 'High-risk medication under strict district quota control. Initiation by Family Medicine Specialist (FMS) only.',
    dosage: 'Individualised prandial dosing immediately before or within 10 min after meals.',
    adverseReaction: 'Hypoglycaemia, lipodystrophy, injection site reactions.',
    contraindications: 'Hypoglycaemia, hypersensitivity to insulin aspart or excipients.',
    interactions: 'Oral antidiabetics, MAOIs, beta-blockers (may mask hypoglycaemia signs).',
    precautions: 'Rotate injection sites within region. Educate on home blood glucose monitoring.',
    isQuota: true,
  },
  {
    id: 'intro-med-4',
    name: 'Empagliflozin 10mg Tablet',
    malBrands: 'MAL17086001A (Jardiance)',
    fukkmSystemGroup: 'Alimentary Tract and Metabolism',
    mdc: 'A10BK03000T1001XX',
    neml: 'Yes',
    methodOfPurchase: 'Contract',
    prescriberCategory: 'A/KK',
    indications: 'Type 2 diabetes with established cardiovascular disease, chronic heart failure.',
    prescribingRestrictions: 'Strict allocation control. Requires baseline eGFR documentation and FMS approval.',
    dosage: '10mg once daily in the morning with or without food. May increase to 25mg OD.',
    adverseReaction: 'Genital mycotic infections, urinary tract infections, volume depletion.',
    contraindications: 'eGFR < 20 mL/min/1.73m², dialysis, history of ketoacidosis.',
    interactions: 'Loop diuretics (increases risk of dehydration), insulin (reduce insulin dose).',
    precautions: 'Temporary discontinuation before elective major surgery to prevent euglycemic DKA.',
    isQuota: true,
  },
  {
    id: 'intro-med-5',
    name: 'Amoxicillin + Clavulanic Acid 625mg Tablet',
    malBrands: 'MAL19950876A (Augmentin, Curam)',
    fukkmSystemGroup: 'Antiinfectives for Systemic Use > Antibacterials for Systemic Use',
    mdc: 'J01CR02000T1001XX',
    neml: 'Yes',
    methodOfPurchase: 'APPL',
    prescriberCategory: 'B',
    indications: 'Lower respiratory tract infections, acute bacterial sinusitis, skin and soft tissue infections, animal bites.',
    prescribingRestrictions: 'Prescribe in accordance with National Antibiotic Guideline (NAG Section C) primary care empirical algorithms.',
    dosage: '625mg (500/125) BD to TDS for 5–7 days depending on clinical infection severity.',
    adverseReaction: 'Diarrhea, nausea, vomiting, candidiasis, maculopapular rash.',
    contraindications: 'History of penicillin hypersensitivity or amoxicillin/clavulanate-associated jaundice/hepatic dysfunction.',
    interactions: 'Methotrexate (decreases clearance), allopurinol (increased risk of rash), oral contraceptives.',
    precautions: 'Dose adjustment in severe renal impairment (CrCl < 30 mL/min). Maintain adequate fluid intake.',
    isQuota: false,
  },
];
